### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by DarthBlack** [quelpa/quelpa#90] opened 2015-09-05 14:57 UTC
I'm getting warnings when I'm running emacs for the first time after adding
```
(package-initialize)
(if (require 'quelpa nil t)
    (quelpa-self-upgrade)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.github.com/quelpa/quelpa/master/bootstrap.el")
    (eval-buffer)))
```
to my init.el file.

Compile log:
```
Leaving directory `/home/[username]/.emacs.d/elpa/package-build-20150905.256'

Compiling file /home/[username]/.emacs.d/elpa/package-build-20150905.256/package-build-pkg.el at [date and time]
Entering directory `/home/[username]/.emacs.d/elpa/package-build-20150905.256/'

Compiling file /home/[username]/.emacs.d/elpa/package-build-20150905.256/package-build.el at [date and time]

Compiling no file at [date and time]
Leaving directory `/home/[username]/.emacs.d/elpa/quelpa-0.0.1'

Compiling file /home/[username]/.emacs.d/elpa/quelpa-0.0.1/quelpa-pkg.el at [date and time]
Entering directory `/home/[username]/.emacs.d/elpa/quelpa-0.0.1/'

Compiling file /home/[username]/.emacs.d/elpa/quelpa-0.0.1/quelpa.el at [date and time]

In quelpa-get-package-desc:
quelpa.el:182:33:Warning: package-tar-file-info called with 1 argument, but
    accepts only 0

In package-build--checkout-url:
quelpa.el:293:31:Warning: reference to free variable
    `package-strip-rcs-id-orig'

In quelpa-package-install-file:
quelpa.el:439:29:Warning: reference to free variable
    `insert-file-contents-literally-orig'

In quelpa-expand-recipe:
quelpa.el:480:14:Warning: called-interactively-p called with 0 arguments, but
    requires 1

In end of data:
quelpa.el:536:1:Warning: the function `package-desc-from-legacy' is not known
    to be defined.
```

**Comment by steckerhalter** [comment] 2015-09-05 18:19
Hi. Nothing to worry about, these are compiler warnings which means that on compiling the .el into .elc the byte compiler is warning that something **could** be wrong. That's what most compilers do. They try to guess from the information they have.

We support Emacs 24.3 and 24.4 hence there are different functions calling conventions for either version and for example on 24.3 the compiler will warn that the function call for 24.4 is "wrong".

**Comment by steckerhalter** [comment] 2015-09-07 07:08
I'm closing this since it is normal behavior by the byte compiler and not a bug/error

**Closed by steckerhalter** 2015-09-07 07:08 UTC
