### ISSUE TITLE
Compile warnings on Emacs 24.5.1

### ISSUE THREAD

**Issue by 23Skidoo** [quelpa/quelpa#108] opened 2016-08-11 14:16 UTC
Using the [recommended installation method](https://github.com/quelpa/quelpa#installation), I get the following during bootstrap:

```
Compiling file /home/refold/.emacs.d/elpa/quelpa-0.0.1/quelpa.el at Thu Aug 11 15:59:53 2016

In quelpa-get-package-desc:
quelpa.el:202:33:Warning: package-tar-file-info called with 1 argument, but
    accepts only 0

In end of data:
quelpa.el:651:1:Warning: the function `package-desc-from-legacy' is not known
    to be defined.
```

**Comment by steckerhalter** [comment] 2016-08-11 15:32
Yes, one warning is because of this code:

```cl
                           (if (help-function-arglist 'package-tar-file-info)
                               ;; legacy `package-tar-file-info' requires an arg
                               (package-tar-file-info file)
                             (with-no-warnings (package-tar-file-info)))))))))
```

The function the compiler warns about is executed depending on the emacs version either with or without argument. Compiler warnings are not errors but hints that something *might* be wrong (which is often not the case but intended like here).

The other warning is similar. There's nothing wrong there even though the compiler thinks so.

See also this issue: https://github.com/quelpa/quelpa/issues/90

**Comment by 23Skidoo** [comment] 2016-08-11 19:26
Well, it's nice to keep code warning-free, because spurious warnings are a nuisance and can drown out real ones. But it's up to you of course.

**Comment by steckerhalter** [comment] 2016-08-11 22:07
If you know how make it warning-free, feel free to suggest how. I don't know in this case, with compilation warnings. If it is possible the compiler should be instructed not to warn about this.

**Comment by 23Skidoo** [comment] 2016-08-11 22:12
My elisp is rusty, but I remember fixing a similar issue with macros once. The macro checked Emacs version at compile-time and generated a compatibility shim.

**Comment by steckerhalter** [comment] 2016-08-12 06:12
Most elisp packages produce compiler warnings. Just as most compiled programs (like C) produce compiler warnings. Frankly this is information is for the developer and not for the user. So as a user you could turn off the warnings with `(setq byte-compile-warnings nil)` if you want.

I will leave it like this because it's not trivial to suppress them and also it's not a bug or something that causes problems.

**Comment by steckerhalter** [comment] 2016-08-18 10:47
I'm closing this for said reasons. If you do find a way to make the warnings disappear, please contribute it via PR. Thank you for bringing this up and have a nice day!

**Closed by steckerhalter** 2016-08-18 10:47 UTC
