### ISSUE TITLE
"Search failed: Last edited <regex>" causes checkout of goto-chg to fail

### ISSUE THREAD

**Issue by aw1621107** [quelpa/quelpa#77] opened 2015-07-26 21:17 UTC
This happens both with my full init.el and a bare-bones bootstrap + `(quelpa 'evil)` init.el. Running emacs 25.0.50.1, and tried it on 24.5 also. Running zsh on OS X 10.11. I tried the fix that worked for #65, but it didn't seem to do anything.

```
Wrote /Users/awang/.emacs.d/quelpa/packages/evil-readme.txt
Parsing tar file...done
Fetcher: wiki
Contacting host: www.emacswiki.org:80
Wrote /Users/awang/.emacs.d/quelpa/build/goto-chg/goto-chg.el
goto-chg.el has changed - checking mod time
Waiting 3.00 secs before hitting Emacswiki again
Contacting host: www.emacswiki.org:80
Quelpa: failed to checkout `goto-chg': `Search failed: "Last edited \\([0-9]\\{4\\}-[0-9]\\{2\\}-\
  [0-9]\\{2\\} [0-9]\\{2\\}:[0-9]\\{2\\} [A-Z]\\{3\\}\\)"'
Parsing tar file...done
For information about GNU Emacs and the GNU system, type C-h C-a.
```

If more information is required I'll be happy to provide it.

**Comment by wasamasa** [comment] 2015-07-27 08:24
Hmm, can't even get `goto-chg` to build here:

```
Fetcher: wiki
Contacting host: www.emacswiki.org:80
Wrote /home/wasa/.emacs.d/quelpa/build/goto-chg/goto-chg.el
goto-chg.el has changed - checking mod time
Waiting 3.00 secs before hitting Emacswiki again
Contacting host: www.emacswiki.org:80
File: goto-chg.el.stamp
```

**Comment by wasamasa** [comment] 2015-07-27 09:22
It does work on a test branch with Travis, so it must have been me screwing up my local test. Could you provide more information about your Emacs setup and perhaps pastebin the build files Quelpa did fetch?

**Comment by aw1621107** [comment] 2015-07-27 13:28
....Well, it seems I can't reproduce the issue any more. Don't remember changing anything, so not really sure why things are working all of a sudden. Guess this means issue closed?

**Comment by aw1621107** [comment] 2015-07-30 22:11
Aaand now it's happening again, but to open-junk-file. Fun.

**Comment by steckerhalter** [comment] 2015-07-31 04:35
I'm just guessing but to me it this:

```
Contacting host: www.emacswiki.org:80
Quelpa: failed to checkout `goto-chg': `Search failed: "Last edited \\([0-9]\\{4\\}-[0-9]\\{2\\}-\
  [0-9]\\{2\\} [0-9]\\{2\\}:[0-9]\\{2\\} [A-Z]\\{3\\}\\)"'
```

looks like it tried to download `goto-chg` from emacswiki and then fails to parse the file (probably because the download returned and empty file?). This would explain that it only happens sometimes.

And since `open-junk-file` is also from emacswiki it supports my  theory :)

**Comment by steckerhalter** [comment] 2015-07-31 07:28
I'm getting the same error with `open-junk-file`. The download url is http://www.emacswiki.org/emacs/download/open-junk-file.el which **should** deliver plain elisp but instead it returns html which of course cannot be processed further.

**Comment by wasamasa** [comment] 2015-07-31 07:35
Delivers plain text for me here. Must be the wiki randomly acting up.

Oh and us using a wiki for code hosting. That's just terribad.

**Comment by steckerhalter** [comment] 2015-07-31 07:37
Did you check in the browser? It just *looks* like plain text...

**Comment by steckerhalter** [comment] 2015-07-31 07:38
I mean it's html with the code wrapped in <pre></pre>

**Comment by wasamasa** [comment] 2015-07-31 07:50
Yes, I've verified it in Firefox' network tab.

**Comment by steckerhalter** [comment] 2015-07-31 07:58
And if you download in Emacs? `(switch-to-buffer (url-retrieve-synchronously "http://www.emacswiki.org/emacs/open-junk-file.el"))`

**Comment by wasamasa** [comment] 2015-07-31 08:30
Well, would you look at that.

**Comment by steckerhalter** [comment] 2015-07-31 08:42
Well, I get back HTML in the browser and in Emacs. Even using different ISPs. 

@aw1621107 can you run:

```cl
(switch-to-buffer (url-retrieve-synchronously "http://www.emacswiki.org/emacs/open-junk-file.el"))
```

in Emacs *scratch* buffer and see if the content ist HTML or not?

**Comment by vyp** [comment] 2015-07-31 08:59
FWIW I get HTML too when doing:

    (switch-to-buffer (url-retrieve-synchronously "http://www.emacswiki.org/emacs/open-junk-file.el"))

Figured it would help that more people confirm it. But in my browser it looks to be plain text (even with view source and when doing "Save Page As"). How do I check the mime type in a browser?

**Comment by wasamasa** [comment] 2015-07-31 09:02
`Ctrl-Shift-Q` to open the network tab, then redo the request with `F5`.

**Comment by vyp** [comment] 2015-07-31 09:02
@steckerhalter But when doing:

   (switch-to-buffer (url-retrieve-synchronously "http://www.emacswiki.org/emacs/download/open-junk-file.el"))

as in the first time you linked it, I get plain text (i.e. elisp with a header). http://www.emacswiki.org/emacs/open-junk-file.el *is* a html page in the browser (rendered). Is this supposed to be plain text with `url-retrieve-synchronously`?

**Comment by vyp** [comment] 2015-07-31 09:08
@wasamasa Thanks it just says type "plain". Assuming that just means "text/plain".

**Comment by steckerhalter** [comment] 2015-07-31 09:19
It seems to vary. Now I get plain text on one system and HTML on another (I was referring to the actual content not the content-type).

I **believe** it was html content on the system that now shows just text

**Comment by wasamasa** [comment] 2015-07-31 10:41
Now I get it in HTML, too. Let's bug @nicferrier about this.

**Comment by wasamasa** [comment] 2015-07-31 10:43
Um. Are you sure you're not mixing up http://www.emacswiki.org/emacs/download/open-junk-file.el with http://www.emacswiki.org/emacs/open-junk-file.el or something other silly like that?

**Comment by steckerhalter** [comment] 2015-07-31 10:59
right, sorry, I pasted in the wrong link into the code snippet. I'll check again

**Comment by steckerhalter** [comment] 2015-07-31 11:06
anyways, I can't reproduce it now. this morning I got:

```cl
Quelpa: failed to checkout `open-junk-file': `Search failed: "Last edited \\([0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\} [0-9]\\{2\\}:[0-9]\\{2\\} [A-Z]\\{3\\}\\)"'
```

and now I can install `open-junk-file` without any errors.

**Comment by steckerhalter** [comment] 2015-07-31 11:12
ok, it's happening again now in: https://github.com/milkypostman/melpa/blob/master/package-build.el#L307

```cl
               (with-current-buffer (package-build--with-wiki-rate-limit
                                     (url-retrieve-synchronously wiki-url))
```

debugging this tells me `wiki-url` is:

     "http://www.emacswiki.org/emacs/open-junk-file.el"

so the wrong url is in `package-build` ?

**Comment by wasamasa** [comment] 2015-07-31 11:22
package-build.el is using `wiki-url` to retrieve metadata (and `download-url` for the file to actually retrieve), so maybe the issue is that the metadata does not always show up...

**Comment by steckerhalter** [comment] 2015-07-31 14:07
oh yes, I see what you mean. I assumed it's the code that is fetched there but it's just trying to find `Last-edited` and that's what it cannot find sometimes.

**Comment by aw1621107** [comment] 2015-07-31 14:22
@steckerhalter At this time it looks like regular elisp, and quelpa seems to have installed it without any problem when I booted up emacs.

**Comment by steckerhalter** [comment] 2015-07-31 14:35
@aw1621107 Yes, apparently the issue is not the elisp itself but the metadata that is fetched from emacswiki before that. It seems that sometimes it does not contain the `Last edited` string which it is trying to find (which is usually on the bottom of the page http://www.emacswiki.org/emacs/open-junk-file.el)

**Comment by steckerhalter** [comment] 2015-08-06 08:34
looks like this a problem with the emacswiki, can we close it?

**Comment by wasamasa** [comment] 2015-08-06 08:35
Let's at the very least open an issue on its bug tracker before closing this.

**Comment by steckerhalter** [comment] 2015-08-07 18:38
I don't know... it was probably a temporary glitch and currently cannot be reproduced

**Comment by steckerhalter** [comment] 2015-08-18 19:20
If it happens again we can still open up a an issue...

**Comment by steckerhalter** [comment] 2015-08-19 19:09
so now I got it:

```
ノート このページを編集 他のリビジョンを見る 管理
最終編集 2013-01-31 07:20 UTC rubikitch による (差分)
```

on http://www.emacswiki.org/emacs/open-junk-file.el

so the info `package-build` is trying to get `Last edited ...` is in japanese currently

**Comment by aw1621107** [comment] 2015-08-19 19:20
FWIW `goto-chg` is also [in japanese](http://www.emacswiki.org/emacs/GotoChg)

**Comment by steckerhalter** [comment] 2015-08-23 06:11
I have made a PR so the date is fetched directly from the http headers when the file is fetched the first time. With this the html is no longer even loaded or considered:

https://github.com/milkypostman/melpa/pull/3038

**Closed by steckerhalter** 2015-08-23 06:11 UTC
