### ISSUE TITLE
quelpa install a package error

### ISSUE THREAD

**Issue by stardiviner** [quelpa/quelpa#140] opened 2017-12-19 04:54 UTC
# Table of Contents

1.  [config](#org95dc31a)
2.  [error](#orgd720d54)

<a id="org95dc31a"></a>

# config

    (use-package pdf-tools-org
        :quelpa (pdf-tools-org :fetcher github :repo "machc/pdf-tools-org")
        :init
        (add-hook 'after-save-hook
                  (lambda ()
                    (when (eq major-mode 'pdf-view-mode)
                      (pdf-tools-org-export-to-org))))
        )

But this config works:

    (use-package arduino-mode
      ;; :ensure t
      :ensure-system-package arduino
      ;; TODO: switch to official package after the maintainer accepted new PRs.
      ;; https://github.com/bookest/arduino-mode/network
      ;;
      ;; [[file:~/Org/Projects/Code.org::*arduino-mode%20has%20many%20errors][arduino-mode has many errors]]
      ;; 
      :quelpa (arduino-mode :fetcher github :repo "mavit/arduino-mode")
      ;; :bind (:map arduino-mode-map
      ;;             ("C-c C-c" . arduino-upload))
      :config
      (setq arduino-font-lock-extra-types t)
      )

<a id="orgd720d54"></a>

# error

    Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
      quelpa-package-install((pdf-tools-org :fetcher github :repo "machc/pdf-tools-org"))
      quelpa((pdf-tools-org :fetcher github :repo "machc/pdf-tools-org"))
      apply(quelpa (pdf-tools-org :fetcher github :repo "machc/pdf-tools-org"))
      (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'pdf-tools-org)) nil (apply 'quelpa '((pdf-tools-org :fetcher github :repo "machc/pdf-tools-org"))))
      (progn (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'pdf-tools-org)) nil (apply 'quelpa '((pdf-tools-org :fetcher github :repo "machc/pdf-tools-org")))) (defvar use-package--warning371 (function (lambda (keyword err) (let ((msg (format "%s/%s: %s" 'pdf-tools-org keyword (error-message-string err)))) (display-warning 'use-package msg :error))))) (condition-case err (progn (condition-case err (add-hook 'after-save-hook (function (lambda nil (if (eq major-mode 'pdf-view-mode) (progn (pdf-tools-org-export-to-org)))))) ((debug error) (funcall use-package--warning371 :init . #2=(err)))) (let ((now (current-time))) (message "%s..." #1="Loading package pdf-tools-org") (prog1 (if (not (require 'pdf-tools-org nil t)) (display-warning 'use-package (format "Cannot load %s" 'pdf-tools-org) :error)) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" #1# elapsed) (message "%s...done" #1#)))))) ((debug error) (funcall use-package--warning371 :catch . #2#))))
      eval((progn (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'pdf-tools-org)) nil (apply 'quelpa '((pdf-tools-org :fetcher github :repo "machc/pdf-tools-org")))) (defvar use-package--warning371 (function (lambda (keyword err) (let ((msg (format "%s/%s: %s" 'pdf-tools-org keyword (error-message-string err)))) (display-warning 'use-package msg :error))))) (condition-case err (progn (condition-case err (add-hook 'after-save-hook (function (lambda nil (if (eq major-mode 'pdf-view-mode) (progn (pdf-tools-org-export-to-org)))))) ((debug error) (funcall use-package--warning371 :init . #2=(err)))) (let ((now (current-time))) (message "%s..." #1="Loading package pdf-tools-org") (prog1 (if (not (require 'pdf-tools-org nil t)) (display-warning 'use-package (format "Cannot load %s" 'pdf-tools-org) :error)) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" #1# elapsed) (message "%s...done" #1#)))))) ((debug error) (funcall use-package--warning371 :catch . #2#)))) nil)
      elisp--eval-last-sexp(nil)
      eval-last-sexp(nil)
      eros-eval-last-sexp(nil)
      funcall-interactively(eros-eval-last-sexp nil)
      call-interactively(eros-eval-last-sexp nil nil)
      #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x24db8b>)(eros-eval-last-sexp nil nil nil)
      ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x24db8b>) eros-eval-last-sexp)
      apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x24db8b>) eros-eval-last-sexp)
      command-execute(eros-eval-last-sexp)

**Comment by steckerhalter** [comment] 2017-12-19 09:38
I couldn't reproduce, for me:

```emacs-lisp
(use-package pdf-tools-org
    :quelpa (pdf-tools-org :fetcher github :repo "machc/pdf-tools-org")
    :init
    (add-hook 'after-save-hook
              (lambda ()
                (when (eq major-mode 'pdf-view-mode)
                  (pdf-tools-org-export-to-org))))
    )
```
works without any error. It looks like something goes wrong during `quelpa-package-install` hmm, what version of Emacs are you using?

**Comment by stardiviner** [comment] 2017-12-19 10:04
I'm using the latest version of Emacs from `master` branch:
```
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-16
```

**Comment by steckerhalter** [comment] 2017-12-19 10:19
ok, can you find out what's going wrong in `quelpa-package-install` by using edebug?

**Comment by stardiviner** [comment] 2017-12-19 10:23
Ok, I will take a try. Update later.

**Comment by stardiviner** [comment] 2017-12-19 10:35
After edebug on `quelpa-package-install`.
I got result from code `(quelpa-build-package rcp)` and this is the for `file` in let-binding.
```
Result: "/home/stardiviner/.emacs.d/quelpa/packages/pdf-tools-org-20161030.2218.el"
```
I got error on `(quelpa-get-package-desc file)`.
Then I try to edebug on `quelpa-get-package-desc`. But in second edebug, I successly install.
Weird.

**Comment by stardiviner** [comment] 2017-12-19 10:44
I close this for now, if I meet same error then I reopen this issue and add more edebug details. Thanks for instructions.

**Comment by steckerhalter** [comment] 2017-12-19 10:58
allright. yw :grinning:

**Comment by stardiviner** [comment] 2018-01-03 09:19
I got this error again. Here is the new output:
```
Debugger entered: nil
  edebug--display-1(nil 0 before)
  edebug--display(nil 0 before)
  edebug-debugger(0 before nil)
  edebug-before(0)
  (edebug-after (edebug-before 0) 13 (if (edebug-after (edebug-before 1) 5 (plist-member (edebug-after (edebug-before 2) 4 (cdr (edebug-after 0 3 cache-item))) :stable)) (progn (edebug-after (edebug-before 6) 12 (setq quelpa-stable-p (edebug-after (edebug-before 7) 11 (plist-get (edebug-after (edebug-before 8) 10 (cdr (edebug-after 0 9 cache-item))) :stable)))))))
  (lambda nil (edebug-after (edebug-before 0) 13 (if (edebug-after (edebug-before 1) 5 (plist-member (edebug-after (edebug-before 2) 4 (cdr (edebug-after 0 3 cache-item))) :stable)) (progn (edebug-after (edebug-before 6) 12 (setq quelpa-stable-p (edebug-after (edebug-before 7) 11 (plist-get (edebug-after (edebug-before 8) 10 (cdr (edebug-after 0 9 cache-item))) :stable))))))) (edebug-after (edebug-before 14) 32 (if (edebug-after (edebug-before 15) 24 (and (edebug-after 0 16 quelpa-stable-p) (edebug-after (edebug-before 17) 23 (not (edebug-after (edebug-before 18) 22 (plist-get (edebug-after (edebug-before 19) 21 (cdr (edebug-after 0 20 cache-item))) :stable)))))) (progn (edebug-after (edebug-before 25) 31 (let* ((v (edebug-after (edebug-before 27) 29 (last (edebug-after 0 28 cache-item))))) (progn (edebug-after (edebug-before 26) 30 (cdr v)) (setcdr v '(:stable t)))))))))()
  edebug--enter-trace(quelpa-parse-stable ((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t)) (lambda nil (edebug-after (edebug-before 0) 13 (if (edebug-after (edebug-before 1) 5 (plist-member (edebug-after (edebug-before 2) 4 (cdr (edebug-after 0 3 cache-item))) :stable)) (progn (edebug-after (edebug-before 6) 12 (setq quelpa-stable-p (edebug-after (edebug-before 7) 11 (plist-get (edebug-after (edebug-before 8) 10 (cdr (edebug-after 0 9 cache-item))) :stable))))))) (edebug-after (edebug-before 14) 32 (if (edebug-after (edebug-before 15) 24 (and (edebug-after 0 16 quelpa-stable-p) (edebug-after (edebug-before 17) 23 (not (edebug-after (edebug-before 18) 22 (plist-get (edebug-after (edebug-before 19) 21 (cdr (edebug-after 0 20 cache-item))) :stable)))))) (progn (edebug-after (edebug-before 25) 31 (let* ((v (edebug-after (edebug-before 27) 29 (last (edebug-after 0 28 cache-item))))) (progn (edebug-after (edebug-before 26) 30 (cdr v)) (setcdr v '(:stable t))))))))))
  edebug-default-enter(quelpa-parse-stable ((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t)) (lambda nil (edebug-after (edebug-before 0) 13 (if (edebug-after (edebug-before 1) 5 (plist-member (edebug-after (edebug-before 2) 4 (cdr (edebug-after 0 3 cache-item))) :stable)) (progn (edebug-after (edebug-before 6) 12 (setq quelpa-stable-p (edebug-after (edebug-before 7) 11 (plist-get (edebug-after (edebug-before 8) 10 (cdr (edebug-after 0 9 cache-item))) :stable))))))) (edebug-after (edebug-before 14) 32 (if (edebug-after (edebug-before 15) 24 (and (edebug-after 0 16 quelpa-stable-p) (edebug-after (edebug-before 17) 23 (not (edebug-after (edebug-before 18) 22 (plist-get (edebug-after (edebug-before 19) 21 (cdr (edebug-after 0 20 cache-item))) :stable)))))) (progn (edebug-after (edebug-before 25) 31 (let* ((v (edebug-after (edebug-before 27) 29 (last (edebug-after 0 28 cache-item))))) (progn (edebug-after (edebug-before 26) 30 (cdr v)) (setcdr v '(:stable t))))))))))
  edebug-default-enter(quelpa-parse-stable ((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t)) (lambda nil (edebug-after (edebug-before 0) 13 (if (edebug-after (edebug-before 1) 5 (plist-member (edebug-after (edebug-before 2) 4 (cdr (edebug-after 0 3 cache-item))) :stable)) (progn (edebug-after (edebug-before 6) 12 (setq quelpa-stable-p (edebug-after (edebug-before 7) 11 (plist-get (edebug-after (edebug-before 8) 10 (cdr (edebug-after 0 9 cache-item))) :stable))))))) (edebug-after (edebug-before 14) 32 (if (edebug-after (edebug-before 15) 24 (and (edebug-after 0 16 quelpa-stable-p) (edebug-after (edebug-before 17) 23 (not (edebug-after (edebug-before 18) 22 (plist-get (edebug-after (edebug-before 19) 21 (cdr (edebug-after 0 20 cache-item))) :stable)))))) (progn (edebug-after (edebug-before 25) 31 (let* ((v (edebug-after (edebug-before 27) 29 (last (edebug-after 0 28 cache-item))))) (progn (edebug-after (edebug-before 26) 30 (cdr v)) (setcdr v '(:stable t))))))))))
  edebug-enter(quelpa-parse-stable ((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t)) (lambda nil (edebug-after (edebug-before 0) 13 (if (edebug-after (edebug-before 1) 5 (plist-member (edebug-after (edebug-before 2) 4 (cdr (edebug-after 0 3 cache-item))) :stable)) (progn (edebug-after (edebug-before 6) 12 (setq quelpa-stable-p (edebug-after (edebug-before 7) 11 (plist-get (edebug-after (edebug-before 8) 10 (cdr (edebug-after 0 9 cache-item))) :stable))))))) (edebug-after (edebug-before 14) 32 (if (edebug-after (edebug-before 15) 24 (and (edebug-after 0 16 quelpa-stable-p) (edebug-after (edebug-before 17) 23 (not (edebug-after (edebug-before 18) 22 (plist-get (edebug-after (edebug-before 19) 21 (cdr (edebug-after 0 20 cache-item))) :stable)))))) (progn (edebug-after (edebug-before 25) 31 (let* ((v (edebug-after (edebug-before 27) 29 (last (edebug-after 0 28 cache-item))))) (progn (edebug-after (edebug-before 26) 30 (cdr v)) (setcdr v '(:stable t))))))))))
  quelpa-parse-stable((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t))
  (let* ((quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (cache-item (if (symbolp arg) (list arg) arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (quelpa-package-install arg) (quelpa-update-cache cache-item))
  (progn (let* ((quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (cache-item (if (symbolp arg) (list arg) arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (quelpa-package-install arg) (quelpa-update-cache cache-item)))
  (if (quelpa-setup-p) (progn (let* ((quelpa-upgrade-p (if current-prefix-arg t quelpa-upgrade-p)) (quelpa-stable-p quelpa-stable-p) (cache-item (if (symbolp arg) (list arg) arg))) (quelpa-parse-plist plist) (quelpa-parse-stable cache-item) (quelpa-package-install arg) (quelpa-update-cache cache-item))))
  quelpa((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t))
  apply(quelpa (arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t))
  (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'arduino-mode)) nil (apply 'quelpa '((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t))))
  (progn (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'arduino-mode)) nil (apply 'quelpa '((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t)))) 'ede-arduino-preferences-file (defvar use-package--warning386 (function (lambda (keyword err) (let ((msg (format "%s/%s: %s" 'arduino-mode keyword (error-message-string err)))) (display-warning 'use-package msg :error))))) (condition-case err (progn (if (fboundp 'arduino-upload) nil (autoload (function arduino-upload) "arduino-mode" nil t)) (eval-after-load 'arduino-mode (function (lambda nil (let ((now (current-time))) (message "%s..." #1="Loading package ede") (prog1 (if (not (require 'ede nil t)) (display-warning 'use-package (format "Cannot load %s" 'ede) :error) (if (executable-find (symbol-name 'arduino)) nil (async-shell-command "sudo pacman -S arduino"))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" #1# elapsed) (message "%s...done" #1#)))))))) (if (boundp 'arduino-mode-map) (let* ((name #3="C-c C-c") (key (if (vectorp name) name (read-kbd-macro name))) (kdesc (cons (if (stringp name) name (key-description name)) 'arduino-mode-map)) (binding (lookup-key (or arduino-mode-map . #4=(global-map)) key))) (let ((entry (assoc kdesc . #5=(personal-keybindings))) (details (list #2=(function arduino-upload) (if (numberp binding) nil binding)))) (if entry #6=(setcdr entry details) (add-to-list #7='personal-keybindings (cons kdesc . #8=(details))))) (define-key (or arduino-mode-map . #9=(global-map)) key #2#)) (eval-after-load 'arduino-mode (function (lambda nil (let* ((name #3#) (key (if (vectorp name) name (read-kbd-macro name))) (kdesc (cons (if (stringp name) name (key-description name)) 'arduino-mode-map)) (binding (lookup-key (or arduino-mode-map . #4#) key))) (let ((entry (assoc kdesc . #5#)) (details (list #2# (if (numberp binding) nil binding)))) (if entry #6# (add-to-list #7# (cons kdesc . #8#)))) (define-key (or arduino-mode-map . #9#) key #2#))))))) ((debug error) (funcall use-package--warning386 :catch err))))
  eval((progn (if (and quelpa-use-package-inhibit-loading-quelpa (package-installed-p 'arduino-mode)) nil (apply 'quelpa '((arduino-mode :fetcher github :repo "bwachter/arduino-mode" :upgrade t)))) 'ede-arduino-preferences-file (defvar use-package--warning386 (function (lambda (keyword err) (let ((msg (format "%s/%s: %s" 'arduino-mode keyword (error-message-string err)))) (display-warning 'use-package msg :error))))) (condition-case err (progn (if (fboundp 'arduino-upload) nil (autoload (function arduino-upload) "arduino-mode" nil t)) (eval-after-load 'arduino-mode (function (lambda nil (let ((now (current-time))) (message "%s..." #1="Loading package ede") (prog1 (if (not (require 'ede nil t)) (display-warning 'use-package (format "Cannot load %s" 'ede) :error) (if (executable-find (symbol-name 'arduino)) nil (async-shell-command "sudo pacman -S arduino"))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" #1# elapsed) (message "%s...done" #1#)))))))) (if (boundp 'arduino-mode-map) (let* ((name #3="C-c C-c") (key (if (vectorp name) name (read-kbd-macro name))) (kdesc (cons (if (stringp name) name (key-description name)) 'arduino-mode-map)) (binding (lookup-key (or arduino-mode-map . #4=(global-map)) key))) (let ((entry (assoc kdesc . #5=(personal-keybindings))) (details (list #2=(function arduino-upload) (if (numberp binding) nil binding)))) (if entry #6=(setcdr entry details) (add-to-list #7='personal-keybindings (cons kdesc . #8=(details))))) (define-key (or arduino-mode-map . #9=(global-map)) key #2#)) (eval-after-load 'arduino-mode (function (lambda nil (let* ((name #3#) (key (if (vectorp name) name (read-kbd-macro name))) (kdesc (cons (if (stringp name) name (key-description name)) 'arduino-mode-map)) (binding (lookup-key (or arduino-mode-map . #4#) key))) (let ((entry (assoc kdesc . #5#)) (details (list #2# (if (numberp binding) nil binding)))) (if entry #6# (add-to-list #7# (cons kdesc . #8#)))) (define-key (or arduino-mode-map . #9#) key #2#))))))) ((debug error) (funcall use-package--warning386 :catch err)))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
```

**Comment by steckerhalter** [comment] 2018-01-03 09:32
It looks like the error is ocurring in `quelpa-parse-stable` and has something to do with the `:stable` property? It's really hard to tell because this is an edebug trace. Can you produce a normal trace? Also, how does the recipe etc. look like you use?

**Comment by stardiviner** [comment] 2018-01-03 09:58
The use-package recipe:
```elisp
(use-package arduino-mode
  :ensure-system-package arduino
  :load ede
  :preface
  (defvar ede-arduino-preferences-file (expand-file-name "~/.arduino/preferences.txt"))
  :defines ede-arduino-preferences-file
  :quelpa (arduino-mode
           :fetcher github
           :repo "bwachter/arduino-mode"
           :upgrade t) ; "bwachter/arduino-mode", "mavit/arduino-mode"
  :bind (:map arduino-mode-map
              ("C-c C-c" . arduino-upload))
  )
```

Here is the `*edebug-trace*` output:
```
{ quelpa args: ((arduino-mode :fetcher github :repo bwachter/arduino-mode :upgrade t) nil)
:{ quelpa-parse-stable args: ((arduino-mode :fetcher github :repo bwachter/arduino-mode :upgrade t))
:} quelpa-parse-stable result: nil
:{ quelpa-package-install args: ((arduino-mode :fetcher github :repo bwachter/arduino-mode :upgrade t))
::{ quelpa-build-package args: ((arduino-mode :fetcher github :repo bwachter/arduino-mode :upgrade t))
::} quelpa-build-package result: nil
:} quelpa-package-install result: nil
:{ quelpa-update-cache args: ((arduino-mode :fetcher github :repo bwachter/arduino-mode :upgrade t))
```

**Comment by stardiviner** [comment] 2018-01-03 10:00
The error is not from `quelpa-parse-stable`.

**Comment by stardiviner** [comment] 2018-01-03 10:05
In `quelpa-package-install` function, `(quelpa-build-package rcp)` got `nil`. Because `version` is nil in `quelpa-build-package`.

**Comment by steckerhalter** [comment] 2018-01-03 10:28
do you have `quelpa-stable-p` set to `t`?

**Comment by steckerhalter** [comment] 2018-01-03 10:35
I can't reproduce, for me there is no error. Can you find out what is going wrong  in `(quelpa-build-package rcp)` by stepping through with edebug? https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Edebug.html

**Comment by a13** [comment] 2018-02-08 09:45
I have the same issue on emacs-snapshot (27-something) and it's something weird going on there:

I tried to evaluate piece by piece and found that `file` argument is somehow shadowed inside `quelpa-get-package-desc`, so we get `nil` as a result. Renamed it to `package-file` and everything looks fine now.

**Comment by a13** [comment] 2018-02-08 10:02
Well, I tried to remove my elpa and quelpa folders and the clean installation was just fine.

**Comment by steckerhalter** [comment] 2018-02-08 10:05
looks like something gets borked. maybe we can find out sometime.

**Comment by stardiviner** [comment] 2018-02-10 03:56
Seems fixed after upgrading to latest source code `master` compiled Emacs. Don't know which commit works.

**Comment by steckerhalter** [comment] 2018-02-12 10:51
Allright, I encountered this bug too but I'm not on the latest master. I'll check with the latest.

**Comment by steckerhalter** [comment] 2018-02-14 07:39
So I've updated to master and at first I still got the error, but then it disappeared just when I wanted to debug it. Hmm... looks like something in Emacs that was changed and then corrected again?

**Comment by stardiviner** [comment] 2018-02-14 08:40
Me too. It just disappear when I want to debug it. Really ... don't know what to say...

**Comment by steckerhalter** [comment] 2018-02-14 08:52
So I think I might know what's going on. Assumption: Emacs changed something that affects byte-compiling (AFAIK they sometimes do that with new Emacs versions). As soon as the quelpa code is evaled the byte compiled code is overridden and it works again. Now I figured it might be necessary to byte-compile quelpa again so I just removed quelpa and bootstrapped it again. Now it works for me.

**Comment by a13** [comment] 2018-02-14 08:54
>AFAIK they sometimes do that with new Emacs versions

sometimes they really do!

**Comment by steckerhalter** [comment] 2018-02-15 16:07
So it popped up again, the error. Then evaled quelpa.el and it went away. So far no luck finding the source.

**Comment by steckerhalter** [comment] 2018-02-17 05:57
So the error happens in `quelpa-get-package-desc`. When I eval this function unchanged it works. This is definitely odd.

**Comment by steckerhalter** [comment] 2018-02-17 07:16
So deleting `quelpa.elc` makes the error go away, and recompiling it still works. Really looks like a byte-compilation issue, especially since the error that pops up is not even related to the code that runs.

It may even be an Emacs bug, we'll see...

**Comment by a13** [comment] 2018-02-17 13:40
As I said before https://github.com/quelpa/quelpa/issues/140#issuecomment-364057148 - possibly it has something to do with `file` argument name.

**Comment by steckerhalter** [comment] 2018-02-17 19:14
@a13 I don't think so, there's no file arg involved where it fails

**Comment by steckerhalter** [comment] 2018-02-17 19:14
@a13 I don't think so, there's no file arg involved where it fails

**Comment by steckerhalter** [comment] 2018-02-17 20:48
@a13 I have debugged it and the place where it fails is `package-tar-file-info`, it says `(wrong-type-argument arrayp nil)` in a place where there isn't even an array to be expected.

**Comment by steckerhalter** [comment] 2018-02-21 10:54
Is someone still getting this issue? Otherwise I'm going to close it. For me it is gone since I recompiled quelpa.

**Comment by steckerhalter** [comment] 2018-02-23 18:47
No answer, no problem? :smirk: I'm closing this. If there is more trouble you may reopen.

**Closed by steckerhalter** 2018-02-23 18:47 UTC
