### ISSUE TITLE
Error when using quelpa-upgrade-all

### ISSUE THREAD

**Issue by dalanicolai** [quelpa/quelpa#213] opened 2021-03-04 10:12 UTC
I am on Spacemacs, and I have just updated some package in some github repository. I have installed this package with a quelpa recipe in the Spacemacs `additional-packages` in the dotfile.

Now when I try to issue `quelpa-upgrade-all` the package does not get updated. However, the following error shows up in my messages buffer (I paste some extra lines before and after the error to show that other packages pass just fine):
```
Newer package has been installed. Not upgrading.
Fetcher: github
Source: syl20bnr/ox-gfm

Updating /home/dalanicolai/spacemacs/.cache/quelpa/build/ox-gfm/
Newer package has been installed. Not upgrading.
Fetcher: github
Source: dalanicolai/pdf-continuous-scroll-mode.el

Updating /home/dalanicolai/spacemacs/.cache/quelpa/build/pdf-continuous-scroll-mode/
Error: (error Command ’(env LC_ALL=C /usr/bin/timeout -k 60 600 git checkout origin/master)’ exited with non-zero status 1: HEAD is now at 8c25a40 Merge pull request #212 from wyuenho/fix-defcustom-types
'quelpa-20210208.816/
quelpa-20210208.816/quelpa-pkg.el
quelpa-20210208.816/quelpa.el
quelpa-20210208.816/bootstrap.el
2021-02-08 07:16:00 +0000'HEAD is now at 1f38fc3 Minor fix on README.
'2020-12-25 17:01:22 +0800'HEAD is now at 71fb603 Make command log colorful
'2015-12-08 09:52:08 +0200'HEAD is now at 41be8b9 Add basic djvu-occur-mode-map
'2020-12-14 07:44:24 +0100'HEAD is now at 1da1b40 Add translate_text
'2021-03-04 09:40:47 +0800'HEAD is now at 7dad900 On goto, show marks with delay in *evil-marks* buffer
'2021-02-02 12:04:24 +0100'HEAD is now at 352ab00 Org 9 compatibility
'2016-11-14 09:08:31 -0500'error: Your local changes to the following files would be overwritten by checkout:
	pdf-continuous-scroll-mode.el
Please commit your changes or stash them before you switch branches.
Aborting
)
Newer package has been installed. Not upgrading.
Fetcher: github
Source: quelpa/quelpa

Updating /home/dalanicolai/spacemacs/.cache/quelpa/build/quelpa/
Newer package has been installed. Not upgrading.
Fetcher: github
Source: dalanicolai/toc-mode
```
After deleting the `pdf-continuous-scroll-mode/` directory from the `.cache/quelpa/build/` directory and restarting Spacemacs the new version got installed correctly.

Looking at the error, I assume this must be a bug in Quelpa, but maybe it is a Spacemacs bug or somewhere else (just I noticed there was some commit here 24 days ago). However, I am not sure what it means or how to provide more useful information.

So let me know if you would like some more information. And just close this issue if I reported it in the wrong place. I am just notifying you about this for the case that this is a Quelpa bug.

**Comment by kiennq** [comment] 2021-03-13 09:19
```
'2016-11-14 09:08:31 -0500'error: Your local changes to the following files would be overwritten by checkout:
	pdf-continuous-scroll-mode.el
Please commit your changes or stash them before you switch branches.
```

This is by design currently. `Quelpa` is default not forcefully upgrading package that has local change since package developer can make change into those packages, and we don't want to just clear the change without justification from user.

To forcefully update those packages, there's `C-u M-x quelpa-upgrade-all`.

**Comment by dalanicolai** [comment] 2021-03-15 23:38
Ah, that makes sense! Thanks for the reply.

**Comment by kiennq** [comment] 2021-03-16 00:36
Thanks, I will close the issue.

**Closed** 2021-03-16 00:36 UTC
