### ISSUE TITLE
wrong-type-argument package-desc nil

### ISSUE THREAD

**Issue by Zjl37** [quelpa/quelpa#255] opened 2024-10-04 14:21 UTC
Hi, I'm trying to use quelpa to install [`twlz0ne/whitespace4r.el`](https://github.com/twlz0ne/whitespace4r.el), but gets an error:

```elisp
Debugger entered--Lisp error: (wrong-type-argument package-desc nil)
  signal(wrong-type-argument (package-desc nil))
  quelpa-package-install((whitespace4r :fetcher github :repo "twlz0ne/whitespace4r.el" :files ("whitespace4r.el")))
  apply(quelpa-package-install (whitespace4r :fetcher github :repo "twlz0ne/whitespace4r.el" :files ("whitespace4r.el")) nil)
  quelpa((whitespace4r :fetcher github :repo "twlz0ne/whitespace4r.el" :files ("whitespace4r.el")))
  load-with-code-conversion("/home/zjl37/hack/my-emacs-d-rep2/init.el" "/home/zjl37/hack/my-emacs-d-rep2/init.el" t t)
  load("/home/zjl37/hack/my-emacs-d-rep2/init" noerror nomessage)
  #f(compiled-function () #<bytecode 0xc489d3d5bedc791>)()
  #f(compiled-function () #<bytecode -0x4307d7bb01d2857>)()
  handler-bind-1(#f(compiled-function () #<bytecode -0x4307d7bb01d2857>) (error) startup--debug)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x6298dd642d0b217>) #f(compiled-function () #<bytecode -0x1c2a3f46cb0ff110>) t)
  command-line()
  normal-top-level()
```

Here's the minimum `init.el` that can reproduce this error:

```elisp
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("nongnu" . "https://elpa.nongnu.org/nongnu/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-install 'quelpa)
(require 'quelpa)

(quelpa '(whitespace4r :fetcher github
                       :repo "twlz0ne/whitespace4r.el"
                       :files ("whitespace4r.el")))
```

Put this in a clean empty directory, and run `emacs --init-directory=. --debug-init` gives the above stack trace.

Note that the recipie line is copied verbatim from `twlz0ne/whitespace4r.el`'s home page, and it can work when loaded from manually specified load path, so I don't think there's problem with that package. Besides this, I don't have any idea of what's wrong here with quelpa. 

My emacs-version: `GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.2) of 2024-09-21`

**Comment by alphapapa** [comment] 2024-10-05 23:27
> GNU Emacs 31.0.50

I'd suggest trying to reproduce the problem in a released version of Emacs.

**Comment by Zjl37** [comment] 2024-10-06 17:01
> I'd suggest trying to reproduce the problem in a released version of Emacs.

Oh yes, I should have checked that before ask.

I found the problem does not exist in 29.4-2 version, provided by `emacs` or `emacs-nativecomp` package in the `extra` official Arch Linux repository, **nor** can I reproduce the problem in my manually compiled git version (also 31.0.50) today. It seems the problem only exists in the binary distributed by [archlinuxcn](https://github.com/archlinuxcn/repo) which I use, though I failed to build with the exact same configuration options. Thus I highly suspect this is either an upstream bug or a packaging fault at archlinuxcn, but I cant be quite sure -- I never encountered such weird problem before. I have contacted archlinuxcn for confirmation. 

I have not tried packages on other distros.

---

Meanwhile, in the problematic versions of emacs, I did some more debug:

There's an error in the message buffer which I didn't notice earlier:

`Error getting PACKAGE-DESC: (error Can’t read whole string)`

this is emitted in function `quelpa-get-package-desc`, which then calls `package-buffer-info`.

It seems `package-buffer-info` fails for every `.el` file I could find, with the error like this:

```elisp
Debugger entered--Lisp error: (error "Can’t read whole string")
  error("Can't read whole string")
  package-read-from-string("( (emacs \"26.1\") (compat \"30.0.0.0\") (dash \"2.19.1\") (magit-section \"4.1.1\") (seq \"2.24\") (transient \"0.7.6\") (with-editor \"3$
  lm-package-requires()
  package-buffer-info()
  eval((package-buffer-info) t)
  #f(compiled-function () #<bytecode -0xd95c9467bcdbece>)()
  #f(compiled-function () #<bytecode -0x5db3e1955cb81d1>)()
  eval-expression((package-buffer-info) nil nil 127)
  funcall-interactively(eval-expression (package-buffer-info) nil nil 127)
  command-execute(eval-expression)
```

That might mean the problem is not specific to the package `whitespace4r` I wanted to install. In problematic emacs versions, quelpa just can't install anything?!🤔

**Comment by steckerhalter** [comment] 2024-10-06 18:28
It seems like the string is truncated at the end? `(with-editor \"3$`
Something seems to be missing there.

**Comment by Zjl37** [comment] 2024-10-07 02:08
> It seems like the string is truncated at the end? `(with-editor \"3$` 

Oh, I copied this from terminal emacs. The stacktrace is truncated to my terminal width, but I can be sure the files are intact.

**Comment by alphapapa** [comment] 2024-10-07 02:34
> > It seems like the string is truncated at the end? `(with-editor \"3$`
> 
> Oh, I copied this from terminal emacs. The stacktrace is truncated to my terminal width, but I can be sure the files are intact.

The developers need to see the full error message, not a truncated one.

**Comment by Zjl37** [comment] 2024-10-07 02:38
> The developers need to see the full error message, not a truncated one.

Ok, I edited the last comment.

**Comment by alphapapa** [comment] 2024-10-07 03:24
> That might mean the problem is not specific to the package `whitespace4r` I wanted to install. In problematic emacs versions, quelpa just can't install anything?!🤔

Yes, since the error comes from `lm` and `package`, not `quelpa`, that would seem to be a problem inherent to that build, or something like that.  I think this is not a bug in Quelpa, so closing.

**Closed by alphapapa** 2024-10-07 03:24 UTC

**Comment by steckerhalter** [comment] 2024-10-07 05:19
@Zjl37 it's weird. `package-read-from-string` should read a lisp expression from a string but it says `error("Can't read whole string")`. To me the string looks ok. If you want to find out what is wrong then I think you should see why this function gives an error.

**Comment by lualiloon** [comment] 2025-03-04 19:02
Hi, I'm running into the same issue on my setup:
Emacs version: `GNU Emacs 30.1 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.65 Version 12.7.6 (Build 21H1320)) of 2025-02-24`

Has anyone found a workaround for this since it was last discussed?

**Comment by bcc32** [comment] 2025-03-08 22:47
@lualiloon this appears to be an upstream Emacs issue.  See this comment on a [similar issue in Spacemacs](https://github.com/syl20bnr/spacemacs/issues/16619#issuecomment-2708485464) for some context.
